apiVersion: batch/v1
kind: Job
metadata:
  name: scala-job
spec:
  template:
    spec:
      containers:
      - name: scala-datamart
        image: borisvikvik/scala-datamart:1.0
      restartPolicy: Never
