apiVersion: batch/v1
kind: Job
metadata:
  name: scala-job
spec:
  template:
    spec:
      containers:
      - name: scala-datamart
        image: borisvikvik/scala-datamart:latest
        imagePullPolicy: IfNotPresent 
      restartPolicy: Never
