# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"
services:
  #  scala-app:
  #     image: borisvikvik/testspark:1.0  # или имя из docker images
  #     ports:
  #       - "8080:8080"
  #     container_name: scala-container
   namenode:
      build: .
      image: borisvikvik/hadoop-namenode:latest
      hostname: namenode
      command: bash -c "hdfs namenode && hdfs dfs -mkdir /test"
      networks:
        - hadoop-net
      platform: linux/arm64
      ports:
        - 9870:9870
        - 8020:8020
      # env_file:
      #   - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
          HDFS-SITE.XML_dfs.permissions.enabled: false
          HDFS-SITE.XML_dfs.namenode.rpc-address: namenode:8020
          HDFS-SITE.XML_dfs.replication: 1
          HDFS-SITE.XML_dfs.client.use.datanode.hostname: true
          HDFS-SITE.XML_dfs.datanode.use.datanode.hostname: true

      volumes:
      # # - /Users/bw/GITS/ITMO/SPARL_LAB2/data:/data
      - ./core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      # - ./hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
   datanode1:
      build: .
      image: borisvikvik/hadoop-datanode:latest
      command: >
        bash -c "chmod 777 /opt/hadoop/etc/hadoop/hdfs-site.xml && hdfs datanode & yarn nodemanager"
      platform: linux/arm64
      networks:
        - hadoop-net
      ports:
      - "9864:9864"   # DataNode Web UI
      - "9865:9865"
      - "9867:9867"
      # env_file:
      #   - ./config
      environment:
        HDFS-SITE.XML_dfs.datanode.hostname: localhost
        HDFS-SITE.XML_dfs.datanode.address: 0.0.0.0:9867
        HDFS-SITE.XML_dfs.datanode.ipc.address: 0.0.0.0:9865
        HDFS-SITE.XML_dfs.datanode.permissions.enabled: false
      # volumes:
      # - /Users/bw/GITS/ITMO/SPARL_LAB2/data:/data
      # - ./core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      # - ./hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      # - ./mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      # - ./yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
   resourcemanager:
      build: .
      image: borisvikvik/hadoop-resourcemanager:latest
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      platform: linux/arm64
      networks:
        - hadoop-net
      ports:
         - 8088:8088
      # env_file:
      #   - ./config
      volumes:
        - ./test.sh:/opt/test.sh
        - ./core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
        - ./hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
        - ./mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
        - ./yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
   nodemanager:
      build: .
      image: borisvikvik/hadoop-nodemanager:latest
      command: ["yarn", "nodemanager"]
      platform: linux/arm64
      networks:
        - hadoop-net
      volumes:
        - ./core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
        - ./hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
        - ./mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
        - ./yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      # env_file:
      #   - ./config
   spark-py:
    build: ../pyspark_app/
    image: borisvikvik/pyspark_app_test
    # image: 
    deploy:
      resources:
        limits:
          memory: 16G  # Или 16G по вашему Mac M1
        reservations:
          memory: 8G
    command: bash -c "sleep 29 && /var/lib/python src/load.py && /var/lib/python main.py"
    environment:
      - SPARK_EXECUTOR_MEMORY=2g
      - SPARK_DRIVER_MEMORY=8g
      - SPARK_EXECUTOR_CORES=1
      - SPARK_SQL_ADAPTIVE_ENABLED=true
      - SPARK_SQL_FILES_MAX_PARTITION_BYTES=134217728 
    # volumes:
    #   - ../pyspark_app/data:/app/data
    volumes:
        - ../pyspark_app/src/load.py:/app/src/load.py


networks:
  hadoop-net:
    name: hadoop-net
    # external: true