apiVersion: v1
kind: Pod
metadata:
  name: pyspark-debug
spec:
  hostname: pyspark-debug
  containers:
    - name: spark
      image: borisvikvik/pyspark_app_test
      imagePullPolicy: Never
      command: ["sleep", "3600"]
      workingDir: /app
      volumeMounts:
        - name: my-storage
          mountPath: /data
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc